### PR TITLE
Ready for npm.

### PR DESCRIPTION
**Pull request by trusktr**
https://www.npmjs.com/package/system-font

Made you owner.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, but I don't think we need to have these on npm.

**Comment by trusktr** [comment]
@guybedford How do people using standalone SystemJS (without jspm) get packages? Seems like having these on npmjs.org makes it easier for those people to get the package with a simple `npm install system-font` instead of having to open a a browser, go to github, copy the URL then `npm install git+https://github.com/guybedford/system-font.git`.

**Comment by guybedford** [comment]
There are other tools for this sort of thing like Bower, curl. I don't want jspm users using the version from npm, and I don't want to encourage the use of npm for SystemJS on its own either. So I don't see that this is enough of a pain point for plain SystemJS users that I should publish every release of every plugin to npm. If it were apparent that this was a major pain point for users, I would certainly reconsider.

**Comment by trusktr** [comment]
bower, and especially curl, are suboptimal, but I see how they work because with SystemJS, dependencies need to be manually configured, like with RequireJS, which everyone wants to get away from. This is why Browserify and webpack are nice, because they both resolve dependencies the npm way (as in you don't need a config file to map all the dependencies of each dependency), and now jspm resolves dependencies for SystemJS in it's own way.

But considering that SystemJS on it's own has no dependency handling, bower (and curl???) are completely not optimal and require lots of handwork, or custom scripting.

I'd go as far as suggesting that SystemJS have the ability to handle dependencies the NPM way, and let jspm be the addition for the other stuff like it's registry and support non-npm endpoints.

It feels like you dislike npm, and want to just get users away from it (whether that's actually true, I don't know), but reality is that `npm` is currently the best source for packages without a doubt, and webpack and browserify have the competitive advantage because they work with the default npm package resolution mechanism, or whatever it's called.

Suggesting bower is completely impractical to some people (like me, but I'm not the only one) because I'd rather use a tool that wires up dependencies (like jspm, browserify, webpack, or duo). RequireJS is out of the question because it takes too much work. SystemJS is only better than RequireJS because you're not limited to AMD modules, but nonetheless bower+SystemJS isn't inherently better besides the module support. JSPM is what brings magic to the package manangement of SystemJS, but if SystemJS at least worked with NPM packages like browserify and webpack do, you'd certainly draw many more users to the SystemJS community.

**Pull request closed without merging**
