### PR TITLE
Refactor using switch statement

### PR DESCRIPTION
**Pull request by maxnordlund**
This makes it a bit easier to read, and have a slightly smaller footprint.

### CODE REVIEW

**Comment by guybedford** [comment]
Sure, thanks!

**Comment by guybedford** [comment]
@maxnordlund by the way, would you be interested in co-maintaining this project?

**Comment by maxnordlund** [comment]
Sure, it sound like a good idea to raise the :bus: factor.

**Comment by guybedford** [comment]
Thanks! I've moved it to a team repo on SystemJS, and added you. Please ping me to review before releases, but otherwise feel free to contribute to the repo.

**Comment by maxnordlund** [comment]
Ok. It doesn't look like I have access, but that might just be that something is slow. Could you double check? Please

**Comment by guybedford** [comment]
You would have got an email invite to join the team on SystemJS. You should be able to check the invite at https://github.com/systemjs.

**Comment by maxnordlund** [comment]
Aha, I didn't know that. But now it works. Thanks

**Pull request merged**
