### PR TITLE
Change webfont to webfontloader

### PR DESCRIPTION
**Pull request by valorbreak**
Are we using this typekit library? https://github.com/typekit/webfontloader 
or is it a completely different library?

### CODE REVIEW

**Comment by maxnordlund** [comment]
If you check jspm [registry.json](https://github.com/jspm/registry/blob/d64e537b195ad6db0d456610b3e971a1961cdd25/registry.json#L331) and [package-override](https://github.com/jspm/registry/blob/084f836adf5149ca8e5b1cce50cf09876a007a75/package-overrides/github/components/webfontloader%401.5.2.json), you'll see it resolves to [components/webfontloader](/components/webfontloader), which just shims [typekit/webfontloader](/typekit/webfontloader). But that's not too obvious, and we don't have a dependency  on `webfont` which is not good.

**Comment by guybedford** [comment]
Yes we should probably have the jspm dependency properly in the package.json here.

**Comment by maxnordlund** [comment]
I'm not sure what/how to write in the package.json. @guybedford could you take a a stab at it, please?

**Comment by guybedford** [comment]
This should just be:

``` json
{
  "jspm": {
    "dependencies": {
      "webfont": "github:components/webfontloader@^1.6.3"
    }
  }
}
```

in the package.json.

**Comment by valorbreak** [comment]
Thanks a lot!

**Comment by maxnordlund** [comment]
No problem :smile_cat:

**Pull request closed without merging**
